services:
  db:
    image: postgres:17.2
    container_name: go_auth_postgres
    environment:
      POSTGRES_USER: go_auth
      POSTGRES_PASSWORD: go_auth
      POSTGRES_DB: go_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
