services:
  db:
    image: postgres:17.2
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: go_auth
      POSTGRES_PASSWORD: go_auth
      POSTGRES_DB: go_auth
      # POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # POSTGRES_USER: ${POSTGRES_USER}
      # POSTGRES_DB: ${POSTGRES_DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data/

volumes:
  postgres-data:
