// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/amirdashtii/go_auth/internal/core/entities"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAdminRepository creates a new instance of MockAdminRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAdminRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAdminRepository {
	mock := &MockAdminRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAdminRepository is an autogenerated mock type for the AdminRepository type
type MockAdminRepository struct {
	mock.Mock
}

type MockAdminRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAdminRepository) EXPECT() *MockAdminRepository_Expecter {
	return &MockAdminRepository_Expecter{mock: &_m.Mock}
}

// AdminChangeUserRole provides a mock function for the type MockAdminRepository
func (_mock *MockAdminRepository) AdminChangeUserRole(ctx context.Context, id *uuid.UUID, role *entities.RoleType) error {
	ret := _mock.Called(ctx, id, role)

	if len(ret) == 0 {
		panic("no return value specified for AdminChangeUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *entities.RoleType) error); ok {
		r0 = returnFunc(ctx, id, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminRepository_AdminChangeUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminChangeUserRole'
type MockAdminRepository_AdminChangeUserRole_Call struct {
	*mock.Call
}

// AdminChangeUserRole is a helper method to define mock.On call
//   - ctx
//   - id
//   - role
func (_e *MockAdminRepository_Expecter) AdminChangeUserRole(ctx interface{}, id interface{}, role interface{}) *MockAdminRepository_AdminChangeUserRole_Call {
	return &MockAdminRepository_AdminChangeUserRole_Call{Call: _e.mock.On("AdminChangeUserRole", ctx, id, role)}
}

func (_c *MockAdminRepository_AdminChangeUserRole_Call) Run(run func(ctx context.Context, id *uuid.UUID, role *entities.RoleType)) *MockAdminRepository_AdminChangeUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].(*entities.RoleType))
	})
	return _c
}

func (_c *MockAdminRepository_AdminChangeUserRole_Call) Return(err error) *MockAdminRepository_AdminChangeUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminRepository_AdminChangeUserRole_Call) RunAndReturn(run func(ctx context.Context, id *uuid.UUID, role *entities.RoleType) error) *MockAdminRepository_AdminChangeUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// AdminChangeUserStatus provides a mock function for the type MockAdminRepository
func (_mock *MockAdminRepository) AdminChangeUserStatus(ctx context.Context, id *uuid.UUID, status *entities.StatusType) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for AdminChangeUserStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID, *entities.StatusType) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminRepository_AdminChangeUserStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminChangeUserStatus'
type MockAdminRepository_AdminChangeUserStatus_Call struct {
	*mock.Call
}

// AdminChangeUserStatus is a helper method to define mock.On call
//   - ctx
//   - id
//   - status
func (_e *MockAdminRepository_Expecter) AdminChangeUserStatus(ctx interface{}, id interface{}, status interface{}) *MockAdminRepository_AdminChangeUserStatus_Call {
	return &MockAdminRepository_AdminChangeUserStatus_Call{Call: _e.mock.On("AdminChangeUserStatus", ctx, id, status)}
}

func (_c *MockAdminRepository_AdminChangeUserStatus_Call) Run(run func(ctx context.Context, id *uuid.UUID, status *entities.StatusType)) *MockAdminRepository_AdminChangeUserStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID), args[2].(*entities.StatusType))
	})
	return _c
}

func (_c *MockAdminRepository_AdminChangeUserStatus_Call) Return(err error) *MockAdminRepository_AdminChangeUserStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminRepository_AdminChangeUserStatus_Call) RunAndReturn(run func(ctx context.Context, id *uuid.UUID, status *entities.StatusType) error) *MockAdminRepository_AdminChangeUserStatus_Call {
	_c.Call.Return(run)
	return _c
}

// AdminDeleteUser provides a mock function for the type MockAdminRepository
func (_mock *MockAdminRepository) AdminDeleteUser(ctx context.Context, id *uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AdminDeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminRepository_AdminDeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminDeleteUser'
type MockAdminRepository_AdminDeleteUser_Call struct {
	*mock.Call
}

// AdminDeleteUser is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockAdminRepository_Expecter) AdminDeleteUser(ctx interface{}, id interface{}) *MockAdminRepository_AdminDeleteUser_Call {
	return &MockAdminRepository_AdminDeleteUser_Call{Call: _e.mock.On("AdminDeleteUser", ctx, id)}
}

func (_c *MockAdminRepository_AdminDeleteUser_Call) Run(run func(ctx context.Context, id *uuid.UUID)) *MockAdminRepository_AdminDeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_AdminDeleteUser_Call) Return(err error) *MockAdminRepository_AdminDeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminRepository_AdminDeleteUser_Call) RunAndReturn(run func(ctx context.Context, id *uuid.UUID) error) *MockAdminRepository_AdminDeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// AdminGetUserByID provides a mock function for the type MockAdminRepository
func (_mock *MockAdminRepository) AdminGetUserByID(ctx context.Context, id *uuid.UUID) (*entities.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AdminGetUserByID")
	}

	var r0 *entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) (*entities.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *uuid.UUID) *entities.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminRepository_AdminGetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminGetUserByID'
type MockAdminRepository_AdminGetUserByID_Call struct {
	*mock.Call
}

// AdminGetUserByID is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *MockAdminRepository_Expecter) AdminGetUserByID(ctx interface{}, id interface{}) *MockAdminRepository_AdminGetUserByID_Call {
	return &MockAdminRepository_AdminGetUserByID_Call{Call: _e.mock.On("AdminGetUserByID", ctx, id)}
}

func (_c *MockAdminRepository_AdminGetUserByID_Call) Run(run func(ctx context.Context, id *uuid.UUID)) *MockAdminRepository_AdminGetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*uuid.UUID))
	})
	return _c
}

func (_c *MockAdminRepository_AdminGetUserByID_Call) Return(user *entities.User, err error) *MockAdminRepository_AdminGetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAdminRepository_AdminGetUserByID_Call) RunAndReturn(run func(ctx context.Context, id *uuid.UUID) (*entities.User, error)) *MockAdminRepository_AdminGetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// AdminUpdateUser provides a mock function for the type MockAdminRepository
func (_mock *MockAdminRepository) AdminUpdateUser(ctx context.Context, user *entities.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAdminRepository_AdminUpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdateUser'
type MockAdminRepository_AdminUpdateUser_Call struct {
	*mock.Call
}

// AdminUpdateUser is a helper method to define mock.On call
//   - ctx
//   - user
func (_e *MockAdminRepository_Expecter) AdminUpdateUser(ctx interface{}, user interface{}) *MockAdminRepository_AdminUpdateUser_Call {
	return &MockAdminRepository_AdminUpdateUser_Call{Call: _e.mock.On("AdminUpdateUser", ctx, user)}
}

func (_c *MockAdminRepository_AdminUpdateUser_Call) Run(run func(ctx context.Context, user *entities.User)) *MockAdminRepository_AdminUpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.User))
	})
	return _c
}

func (_c *MockAdminRepository_AdminUpdateUser_Call) Return(err error) *MockAdminRepository_AdminUpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAdminRepository_AdminUpdateUser_Call) RunAndReturn(run func(ctx context.Context, user *entities.User) error) *MockAdminRepository_AdminUpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// FindUsers provides a mock function for the type MockAdminRepository
func (_mock *MockAdminRepository) FindUsers(ctx context.Context, status *entities.StatusType, role *entities.RoleType, sort *string, order *string) ([]entities.User, error) {
	ret := _mock.Called(ctx, status, role, sort, order)

	if len(ret) == 0 {
		panic("no return value specified for FindUsers")
	}

	var r0 []entities.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.StatusType, *entities.RoleType, *string, *string) ([]entities.User, error)); ok {
		return returnFunc(ctx, status, role, sort, order)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *entities.StatusType, *entities.RoleType, *string, *string) []entities.User); ok {
		r0 = returnFunc(ctx, status, role, sort, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *entities.StatusType, *entities.RoleType, *string, *string) error); ok {
		r1 = returnFunc(ctx, status, role, sort, order)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAdminRepository_FindUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUsers'
type MockAdminRepository_FindUsers_Call struct {
	*mock.Call
}

// FindUsers is a helper method to define mock.On call
//   - ctx
//   - status
//   - role
//   - sort
//   - order
func (_e *MockAdminRepository_Expecter) FindUsers(ctx interface{}, status interface{}, role interface{}, sort interface{}, order interface{}) *MockAdminRepository_FindUsers_Call {
	return &MockAdminRepository_FindUsers_Call{Call: _e.mock.On("FindUsers", ctx, status, role, sort, order)}
}

func (_c *MockAdminRepository_FindUsers_Call) Run(run func(ctx context.Context, status *entities.StatusType, role *entities.RoleType, sort *string, order *string)) *MockAdminRepository_FindUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*entities.StatusType), args[2].(*entities.RoleType), args[3].(*string), args[4].(*string))
	})
	return _c
}

func (_c *MockAdminRepository_FindUsers_Call) Return(users []entities.User, err error) *MockAdminRepository_FindUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockAdminRepository_FindUsers_Call) RunAndReturn(run func(ctx context.Context, status *entities.StatusType, role *entities.RoleType, sort *string, order *string) ([]entities.User, error)) *MockAdminRepository_FindUsers_Call {
	_c.Call.Return(run)
	return _c
}
